# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param n one parameter of  bivariate density
#' @param a one parameter of  bivariate density
#' @param b one parameter of  bivariate density
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10,2,3)
#' }
#' @export
gibbsC <- function(N, n, a, b) {
    .Call('_StatComp21011_gibbsC', PACKAGE = 'StatComp21011', N, n, a, b)
}

